config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :posts

  # Auth
  get 'registrar', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  is_impressionable

  after_validation :set_slug, only: [:create, :update]
  
  has_rich_text :content

  def to_param
    "#{id}-#{slug}"
  end
  
  private

  def set_slug
    self.slug = title.to_s.parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def authorize
    if current_user.nil?
      redirect_to root_path, alert: "Não autorizado."
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  layout 'welcome'

  before_action :authorize, only: [:index, :new, :create, :edit, :update, :delete]

  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    post = Post.create! post_params
    redirect_to post
  end
  
  def show
    @post = Post.find(params[:id])
    impressionist(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :subtitle, :content)
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  layout 'welcome'
  
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: 'Logado.'
    else
      flash.now.alert = "Email ou senha incorretos."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Deslogado.'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  layout 'welcome'
  
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to @tag
    else
      render 'new'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end

  private

    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'welcome'

  before_action :authorize
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Obrigado por fazer o registro.'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  layout 'welcome'

  def index
    @posts = Post.all
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anderson Brandão</title>

    <meta name="description" content="Página do desenvolvedor web contendo conteúdos relacionados à programação e seus serviços.">
    <link rel="canonical" href="https://andersonbrandao.dev/">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

    <%= favicon_link_tag asset_pack_path('media/images/favicon.png') %>

    <%= stylesheet_pack_tag 'welcome', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!--===========================================================
    Theme Name: Rubiti Institutional
    Author: Anderson Brandão Lustosa
    E-mail: brandao@rubiti.com
    -- LINKS --
    Website: http://www.rubiti.com
    github: @abrandao @rubiti
    ============================================================-->
  </head>

  <body>

    <!-- Sidebar/menu -->
    <nav class="w3-sidebar w3-theme-d3 w3-collapse w3-top w3-padding mySidebar" id="mySidebar"><br>
      <a href="javascript:void(0)" class="w3-button w3-hide-large w3-display-topleft sidebar-anchor" id="w3-close">Fechar Menu</a>
      <div class="w3-container">
      <img src="<%= asset_pack_path 'media/images/me.jpg' %>" class="w3-circle my-picture" alt="Desenvolvedor" />
      <h3 class="w3-padding-8"><b>Anderson Brandão</b></h3>
      <p class="w3-medium">
        Desenvolvedor web focado em Ruby on Rails e fundador da 
        <a href="https://rubiti.com/">rubiti.com</a>
      </p>
    </div>
    <hr>
    <div class="w3-bar-block">
      <%= link_to 'HOME', root_path, class: "w3-bar-item w3-button w3-hover-white", id: "w3-close" %>
    </div>
  </nav>

  <!-- Top menu on small screens -->
  <header class="w3-container w3-top w3-hide-large w3-theme-d3 w3-xlarge w3-padding">
    <div href="javascript:void(0)" class="w3-button w3-theme-l5 w3-margin-right" id="w3-open">&#9776;</div>
    <span>Anderson Brandão</span>
  </header>

  <!-- Overlay effect when opening sidebar on small screens -->
  <div class="w3-overlay w3-hide-large" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

  <!-- !PAGE CONTENT! -->
  <div class="w3-main main-margin">

    <%= yield %>
    
    <!-- End page content -->
  </div>
  <!-- W3.CSS Container -->
  <div class="w3-theme-l4 w3-container w3-padding-32 footer"><p class="w3-right">Desenvolvido por <a href="https://www.rubiti.com" title="rubiti websites" target="_blank" class="w3-hover-opacity">rubiti.com</a></p></div>
  </body>
  <%= javascript_pack_tag 'welcome', 'data-turbolinks-track': 'reload' %>
</html>

app/views/posts/_form.html.erb
<%= form_with scope: :post, url: posts_path, local: true do |form| %>
  <div class="field">
    <%= form.label 'Título' %>
    <%= form.text_field :title%>
  </div>
  <div class="field">
    <%= form.label 'Subtítulo' %>
    <%= form.text_field :subtitle %>
  </div>
  <div class="field">
    <%= form.rich_text_area :content %>
  </div>
  <br>
  <div class="field">
    <%= form.submit "Salvar post", class: "w3-button w3-blue w3-round-xlarge" %>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <div class="field">
    <%= form.label 'Título' %>
    <%= form.text_field :title%>
  </div>
  <div class="field">
    <%= form.label 'Subtítulo' %>
    <%= form.text_field :subtitle %>
  </div>
  <div class="field">
    <%= form.rich_text_area :content %>
  </div>
  <br>
  <div class="field">
    <%= form.submit "Salvar post", class: "w3-button w3-blue w3-round-xlarge" %>
  </div>
<% end %>

<%= button_to 'Postagens', posts_path, class: "w3-button w3-blue w3-round-xlarge", :method => :get %>

app/views/posts/index.html.erb
<h1>Listing Articles</h1>
<table class="w3-table w3-striped w3-bordered">
  <tr class="w3-blue w3-center">
    <th>ID</th>
    <th>Título</th>
    <th class="w3-center">Visualizações</th>
    <th class="w3-center">Data</th>
    <th class="w3-center">Mostrar</th>
    <th class="w3-center">Editar</th>
    <th class="w3-center">Apagar</th>
  </tr>
<% @posts.reverse.each do |post| %>
  <tr>
    <td><%= post.id %></td>
    <td><%= post.title %></td>
    <td class="w3-center"><%= post.impressionist_count  %></td>
    <td class="w3-center"><%= post.created_at.day %>/<%= post.created_at.month %>/<%= post.created_at.year %></td>
    <td class="w3-center"><%= button_to 'Mostrar', post_path(post), class: "w3-button w3-blue w3-round-xlarge", :method => :get %></td>
    <td class="w3-center"><%= button_to 'Editar', edit_post_path(post), class: "w3-button w3-green w3-round-xlarge", :method => :get %></td>
    <td class="w3-center"><%= button_to 'Apagar', post_path(post), class: "w3-button w3-red w3-round-xlarge", method: :delete, data: { confirm: 'Tem certeza?' } %></td>
  </tr>
<% end %>
</table>

<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= button_to "Deslogar", logout_path, :method => :get, class: "w3-button w3-blue w3-round-xlarge" %>
<% end %>
  <%= button_to "Nova postagem", new_post_path, :method => :get, class: "w3-button w3-blue w3-round-xlarge" %>

<hr>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="w3-container" id="services">
  <h2 class="w3-xxlarge"><b><%= @post.title %></b></h2>
  <h3 class="w3-text-theme"><i><%= @post.subtitle %></i></h3>
  <i class="w3-small">Postado em <%= @post.created_at.day %> de <%= @post.created_at.month %> de <%= @post.created_at.year %></i>
  <br>
  <br>
  <%= @post.content %>
  <hr class="w3-round">

app/views/users/new.html.erb
<h1>Registrar</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>O formulário é inválido</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Registrar" %></div>
<% end %>

app/views/welcome/index.html.erb
<% @posts.reverse.each do |post| %>
  <!-- Posts -->
  <div class="w3-container">
    <h2><%= link_to post.title, post_path(post), :method => :get, class: "w3-xxlarge title" %></h2>
    <h3 class="w3-text-theme"><i><%= post.subtitle %></i></h3>
    <%= truncate(strip_tags(post.content.to_s), length: 600) %>
    <%= link_to 'Leia mais', post_path(post), class: "w3-blue" %>
    <hr class="w3-round">
  </div>
<% end %>